# Site settings
title: mkh9293
brief-intro: To be..
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mkh9293.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

github_username: mkh9293
email: mkh9293@gmail.com
linkedIn_username: mkh9293

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 10

plugins:
  - jekyll-paginate
